export const DEFAULT_DAILY_WEAR_GOAL_MINUTES = 1320   // 22h
export const DEFAULT_REMINDER_THRESHOLD_MINUTES = 30
export const DEFAULT_AUTO_CAP_MINUTES = 120
export const DEFAULT_SET_DURATION_DAYS = 7
export const MINUTES_PER_DAY = 1440
export const MAX_SESSION_DURATION_HOURS = 24
export const SYNC_MAX_RETRIES = 3
